### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Viktoriia-Ksenofontova**
all fixes have been made, branches can be merged

### CODE REVIEW

**Comment by oknelvapi** [comment]
Screenshot 2022-01-18 at 21 29 45

**Comment by Viktoriia-Ksenofontova** [comment]
hm... i have only one warning.

**Comment by Viktoriia-Ksenofontova** [comment]
is it definitely happening in the new dev branch?

**Comment by oknelvapi** [comment]
> 

Oh, my fault!

**Review by oknelvapi — APPROVED** [review]

**Pull request merged**
